version: '3.8'

services:
  registry:
    image: distribution/distribution:2.8.3
    ports:
      - '5000:5000'
    labels:
      abwart.enable: true
      abwart.rule.test.revisions: 2
      abwart.rule.test.schedule: 1/30 * * * * *
      abwart.default.revisions: 10
      abwart.default.schedule: 0 2 * * * * *
      abwart.network: test
    networks:
      - test

  abwart:
    image: abwart:local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  test:
    name: test