version: '3.8'

services:
  registry:
    container_name: "test-registry"
    image: registry:2.8.3
    ports:
      # expose port '5000' for local debugging reasons
      - '5000:5000'
    labels:
      abwart.enable: true
      abwart.rule.test.revisions: 2
      abwart.rule.test.schedule: 0 0 1/5 * * *
      abwart.default.revisions: 10
      abwart.default.schedule: 1/30 * * * * *
      abwart.network: test
      abwart.cleanup: 1/30 * * * * *
    networks:
      - test

  abwart:
    build:
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config.yml:/app/config.yml:ro
    networks:
      - test

networks:
  test:
    name: test